export default {
    GameType: 0,
    PlayerList: 1,
    StartGame: 2,
    Leaderboard: 3,
    EndGame: 4,
    Question: 5,
    RoundEnd: 6,
    Voter: 7,
    GameEnded: 8,
    RoundTimer: 9,
    ChatMessage: 10,
    Catagory: 11,
    AwaitingCatagory: 12,
    ResetScreen: 13,
    DrawPixel: 14,
    ResetBoard: 15,
}